### ISSUE TITLE
Add functions to calculate portfolio returns for different sorting methods

### ISSUE THREAD

**Issue by sstoeckl** [tidy-finance/r-tidyfinance#20]
Hey guys, I love your book (the R version) and am heavily using it in my teaching. It would help me a lot if your functions os single- and double-sorting portfolios as well as the rolling beta regressions etc. would be part of the package!

Do you plan on implementing them soon?

**Comment by christophscheuch** [comment]
Thank you for your kind words @sstoeckl 🙏  

We need to clarify the scope of such functions first. For the portfolio sorts: I can think of a function that is called `calculate_portfolio_returns()` with parameters `data`, `sorting_variables`, `n_portfolios`, `sorting_method` (univarite, bivariate-depedent, bivariate-independent) and which returns a tibble with `month`, `portfolio`, `ret_excess_vw`, `ret_excess_ew`. 

For the beta estimation: I think we need to add `roll_capm_estimation()` from the book and add a new function `estimate_beta()` with parameters `data`, `factors` (with default mkt_excess but support for multiple factors), `months_lookback`, `min_obs`  n_cores (with default availableCores() - 1). This function would return `permno`, `month`, beta`. 

Would this be sufficient?

**Comment by sstoeckl** [comment]
Hi @christophscheuch thanks for your prompt reply and the suggestions!

If I could come up with a wish, then I would also add fama-macbeth regressions (price_of_risk - I understand that this is not straightforward, as it requires nesting data appropriately, etc).

**Comment by voigtstefan** [comment]
> Thank you for your kind words @sstoeckl 🙏
> 
> We need to clarify the scope of such functions first.
> 
> For the portfolio sorts: I can think of a function that is called `calculate_portfolio_returns()` with parameters `data`, `sorting_variables`, `n_portfolios`, `sorting_method` (univarite, bivariate-depedent, bivariate-independent), `lag_method` (fama-frech, 6-months, mixed) and which returns a tibble with `month`, `portfolio`, `ret_excess_vw`, `ret_excess_ew`.
> 
> For the beta estimation: I think we need to add `roll_capm_estimation()` from the book and add a new function `estimate_beta()` with parameters `data`, `factors` (with default mkt_excess but support for multiple factors), `months_lookback`, `min_obs` n_cores (with default availableCores() - 1). This function would return a tibble with `permno`, `month`, `beta` (or beta_mkt_excess, beta_hml, beta_smb etc.).
> 
> Would this be sufficient?

Presumably there should also be a distinction between the data and used to build portfolios and the data used to build breakpoints - but I am a bit unsure how to map this to general use cases that go beyond listing exchanges.

**Comment by christophscheuch** [comment]
@voigtstefan can you give me specific examples where the data for portfolios and breakpoints are different? 

I started drafting the calculate_portfolio_returns() function today and also think it makes more sense to make it narrower. For instance, the lag method should probably not be in the scope of the function because the lags might depend on the corresponding variable.

**Comment by voigtstefan** [comment]
Example: breakpoints based on NYSE listed stocks and sorting based on all CRSP stocks. For that reason we split the chain in tidy-finance.org and first computed breakpoints, then applied those.

Not sure if there are other use cases but the one above is definitely relevant. We may have an optional additional argument which takes a 2nd dataset (e.g. filter by listing_exchange==NYSE) to compute breakpoints based on that one. If the argument is empty, just use the default dataset. That way, users can provide their own fancy distinction between breakpoints computation and portfolio construction.

**Comment by voigtstefan** [comment]
To clarify: the argument could be "breakpoint_data = data", defaulting to data.

**Comment by christophscheuch** [comment]
Maybe another scenario is creating breakpoints based on US stocks and using these to sort European stocks (not sure how much sense that makes though). Just to keep it here as another potential case to consider when designing the functions.

**Comment by patrick-weiss** [comment]
I made a first draft of some functions as the basis for further discussions. The idea is to allow for single, dependent double, and independent double sorts both with monthly and annual rebalancing (portfolios assigned in June). 

Supplying external breakpoints seems possible by changing the `assign_portfolio()` function accordingly. Would we want to do this for all flavors of the portfolio sort? I think this puts some strain on the definition of such breakpoints, particularly for dependent sorts.

Additionally, I want to supply a function to lag variables and merge them back. Probably, this is useful beyond portfolio sorts.
