### ISSUE TITLE
In download_X() functions, make types more accessible

### ISSUE THREAD

**Issue by patrick-weiss** [tidy-finance/r-tidyfinance#22]
After using the download functions in a new project, I found the types not clear enough for the user. Should we highlight the types in the documentation?

Additionally, the function list_supported_types() should be mentioned if option 'type' is not supported. We might also consider an option in list_supported_types() to only show domain-specific types, and an option to automatically print all available types (instead of the tibble default length).

What do you think?

**Comment by christophscheuch** [comment]
I support all of your suggestions 👍🏻
