### ISSUE TITLE
crsp_daily add support for columns in msenames (v1) and stksecurityinfohist (v2)

### ISSUE THREAD

**Issue by patrick-weiss** [tidy-finance/r-tidyfinance#29]
For example, there are use cases loading CRSP v1 daily returns alongside variables like `exchcd`, which are not present in the current data. 

I suggest leveraging CRSP msenames / stksecurityinfohist for this information (for v2 this only means to relax the select() at the end). Additionally, add the `shrcd` filter vor v1.

**Comment by patrick-weiss** [comment]
Should also check if removing this restriction for monthly makes sense.

Additionally, check if we create multiple variables with the same name but different content (e.g., siccd not having the same meaning).

**Comment by christophscheuch** [comment]
Maybe we add a new data type to pull time-invariant stock-specific information and use the existing CRSP types only for time-varying historical stock info? 

In any case, looking forward to the PR.
