### ISSUE TITLE
Make start_date and end_date optional in `download_data() `

### ISSUE THREAD

**Issue by voigtstefan** [tidy-finance/r-tidyfinance#34]
E.g. `download_data_factors_ff` requires to set a start and end date. Both choices should be optional.

**Comment by christophscheuch** [comment]
I think a global solution would be nice, not just for frenchdata (which is always fully downloaded). Maybe we add sensible defaults to WRDS data as well and print a message to the user if he/she does not provide any dates where the message says something like "Data set contains full date range as default" or "Data set includes data from X to Y as default. Consider using start_date and end_date".

**Comment by patrick-weiss** [comment]
Great idea! I think Christoph's second statement is better. For CRSP and Compustat data, I suggest using a short time range (e.g., from today - 2y to today, or similar) so that it loads quickly.
