### ISSUE TITLE
R version 4.1.0 does not support named placeholder

### ISSUE THREAD

**Issue by m-muecke** [tidy-finance/r-tidyfinance#55]
In the following the pipe is used for the named placeholder for rhs: https://github.com/tidy-finance/r-tidyfinance/blob/main/R/download_data_factors.R#L115 this feature was only released in R >= 4.2.0 and the current package version depends on R >= 4.1.0 https://cran.r-project.org/doc/manuals/r-release/NEWS.html

**Comment by christophscheuch** [comment]
Good catch! I'll implement it without the named placeholder to have a broader support.
