### ISSUE TITLE
Use explicit NULL for optional arguments in functions

### ISSUE THREAD

**Issue by m-muecke** [tidy-finance/r-tidyfinance#62]
The following really comes down to preference:

Currently the package uses both missing and `NULL` for optional arguments.
I would suggest using one convention and would personally recommend the tidyverse principle of always giving optional args default values. For reference see the design guide: https://design.tidyverse.org/required-no-defaults.html#whats-the-pattern and a concrete example: https://github.com/tidyverse/dplyr/blob/main/R/across.R#L191. tidyverse packages basically always use `NULL` for optional defaults

**Comment by m-muecke** [comment]
On a related note I would recommend the use of implicit returns where possible, since this is also mixed in the package with explicit returns and implicit. tidyverse and general R style is widely using implicit returns and only explicit returns when required (i.e. more of a functional style), but that again is something very opinionated

**Comment by christophscheuch** [comment]
About optional arguments: with the tidyverse design pattern as a backup, I support moving everything back to using explicit NULLs for optional arguments. I originally designed it that way, but recently thought that using missing() might be a more elegant solution (I was wrong). 

Ad implicit returns: if the function unfolds linearly (last step returns the result), then I wouldn't use return(). For instance, the explicit return in assign_portfolio() is redundant. If there are different paths for the function like in estimate_model(), then I think keeping return() makes sense.
