### ISSUE TITLE
Provide function to set WRDS credentials as environment variables

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/r-tidyfinance#8]
The get_wrds_connection() function uses environment variables to establish a connection to WRDS. Implement the following:
- Ask users for user name and password
- Also update .gitignore if it is available
- Add checks to get_wrds_connection() if environment variables are set and throw error message otherwise

**Comment by patrick-weiss** [comment]
"Add checks to get_wrds_connection() if environment variables are set and throw error message otherwise" - or go back to asking for username and password?
