### ISSUE TITLE
Remove hard-coded column name requirements

### ISSUE THREAD

**Issue by voigtstefan** [tidy-finance/r-tidyfinance#83]
I propose to introduce key function arguments such as `data_options = list(id = “id”, date = “date”)` to remove hard-coded column name requirements. Right now, fx, to perform portfolio sorts you'll need a column named permno, potentially one which is called exchange, mktcap_lag, etc. Depending on the user, these columns may be named differently and I do not see a reason why we should enforce naming conventions.

**Comment by voigtstefan** [comment]
List of currently implemented hard-coded column names

- [ ] compute_portfolio_returns (ret_excess, mktcap_lag)
- [ ] compute_long_short_returns (date, portfolio, ret_ (?))
- [ ] compute_breakpoints (exchange)
- [ ] estimate_fama_macbeth (date)
- [ ] estimate_betas (date, permno)

Currently considering a new functions argument `data_options` (named list with characters) as a global, consistent solution:

Example for `estimate_betas`

`data_options = list(id = "permno", date ="date")`

Open points

- [ ] Naming conventions: I would choose `id `for (firm) identifiers, `date `for dates, `return `for returns, and the current column names (mktcap_lag and portfolio) for specific cases. 
- [ ] What about defaults? Leaving the inputs empty would put partially redundant work on readers of TFWR. I tend to choose defaults which are in line with the book and a clarifying error (e.g. "Required column {arg} is not present in the data. Use the argument data_options to identify the corresponding column names in your dataset).

**Comment by christophscheuch** [comment]
`return` is unfortunately a very bad new because of `return()`. The other names sounds good to me!

I'd also use the TFWR defaults + clear error message.

**Comment by patrick-weiss** [comment]
Great idea if the defaults work properly (i.e., with the CRSP & Compustat naming conventions - or tidyfinance).

Should this setting also affect `download_data()`? There is an argument that we could use it to define the respective variables according to the options.
