### ISSUE TITLE
Add support for downloading Open Source Asset Pricing factor data

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/r-tidyfinance#88]
Info: https://www.openassetpricing.com/data/

Code:
```
url <- "https://drive.google.com/uc?export=download&id=1JyhcF5PRKHcputlioxlu5j5GyLo4JYyY"
raw_data <- as_tibble(read.csv(url))
```

Question: how to name the download_* function and the type to be concise and avoid "open_source_asset_pricing" - maybe "osap"?

**Comment by voigtstefan** [comment]
osap sounds fine.
Eventually it would be useful to check/clean the column names before shipping
