### ISSUE TITLE
Add support to download data from Nasdaq stock screener

### ISSUE THREAD

**Issue by christophscheuch** [tidy-finance/r-tidyfinance#90]
Simple JSON for NYSE, NASDAQ, AMEX: 
https://api.nasdaq.com/api/screener/stocks?tableonly=true&exchange=NYSE&download=true

Question: how to call this function?

**Comment by voigtstefan** [comment]
I guess only the symbols (and maybe ipo dates) are of relevance. I'd call it download_tickers("NYSE")? For me, this function serves the only purpose to feed it into download_yf afterwards (I guess)

**Comment by christophscheuch** [comment]
I'll use download_data_symbols() because we use symbols everywhere, not tickers (also in the books).
